# This is a basic workflow to help you get started with Actions

name: GAE Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    env:
      SECRET: '${{ secrets.APP_SECRET }}'
      AUTH0_ID: '${{ secrets.AUTH0_CLIENT_ID }}'
      AUTH0_SECRET: '${{ secrets.AUTH0_CLIENT_SECRET }}'
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
